openapi: 3.0.0
info:
  title: Workflow Building Block API
  description: The GovStack Workflow Building Block API
  contact:
    email: workflow@discourse.govstack.global
  license:
    name: MIT
  version: 1.0.0
tags:
  - name: v1
    description:
      This endpoint is a requirement for the v1 workflow engine BB
      specification.
  - name: admins
    description:
      Endpoints that are available to administrators of this workflow BB
      instance (e.g., to configure the workflow BB.)
  - name: developers
    description:
      Endpoints that are available to other GovStack developers/applications to
      discover, instantiate, and monitor processes.
  - name: Design
    description: Endpoints that are used to configure workflows
  - name: Runtime
    description: Endpoints that are used to execute and monitor workflows
paths:
  /processes:
    get:
      tags:
        - v1
        - developers
        - Design
      summary: returns a list of workflow processes i.e., definitions of process
      description: Listing of all processes with basic information
      operationId: getProcessList
      responses:
        '200':
          description: list of processes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Process'
              example:
                ArrayOfProcesses:
                  type: array
                  example:
                    - id: ReviewInvoice:1:bf20fe53-5548-11ed-9dd4-0242ac150002
                      key: ReviewInvoice
                      category: http://bpmn.io/schema/bpmn
                      version: 1
                    - id: invoice:1:bf2013f1-5548-11ed-9dd4-0242ac150002
                      key: invoice
                      category: http://www.omg.org/spec/BPMN/20100524/MODEL
                      version: 1
        '404':
          description: Processes not found
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - admins
        - Design
      summary: adds a new process
      description: Adds a process to the system
      operationId: addProcess
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessDefinition'
      responses:
        '201':
          description: Process successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Process'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /processes/{processId}:
    get:
      tags:
        - v1
        - developers
        - Design
      summary: returns detailed information about a process
      description: |
        Pass in the ID of the process and it will return all information about that process
      operationId: getProcess
      parameters:
        - $ref: '#/components/parameters/processIdParam'
      responses:
        '200':
          description: process found and representation returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Process'
        '404':
          description: Process not found
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - Design
        - admins
      parameters:
        - $ref: '#/components/parameters/processIdParam'
      summary: updates an existing process
      description: Updates a process on the system
      operationId: updateProcess
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '204':
          description: Process successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Process'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - admins
      parameters:
        - $ref: '#/components/parameters/processIdParam'
      summary: deletes an existing process
      description: Deletes a process on the system
      operationId: deleteProcess
      responses:
        '200':
          description: Process successfully deleted
        '500':
          $ref: '#/components/responses/InternalServerError'
  /processes/{processId}/start:
    post:
      tags:
        - v1
        - developers
        - Runtime
      summary: instantiates a process execution; creates a process instance
      operationId: start
      description:
        Create a process instance and register it with the execution engine
      requestBody:
        description:
          Process instance initiation payload (initial 'state' for the process)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessInstancePayload'
      parameters:
        - $ref: '#/components/parameters/processIdParam'
      responses:
        '201':
          description:
            Process started; registered for execution with unique process
            instance ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 95aef406-3a7a-11e5-85b6-dafa20524153
                    description: The unique process instance ID.
                  processRef:
                    type: string
                    example: invoice:1:15e97a1c-312d-11e5-aca3-a0e120524153
                    description: The process definition ID.
                  suspended:
                    type: boolean
                    example: false
                    description: States if process instance is suspended
                  ended:
                    type: boolean
                    example: false
                    description: States if process instance has ended
                  state:
                    type: string
                    example: running
                    description: Provides the execution state of the process instance
        '404':
          description: Process not found
        '500':
          $ref: '#/components/responses/InternalServerError'
  /instances/:
    get:
      tags:
        - v1
        - developers
        - Runtime
      summary:
        returns a list of process instances; can be constrained by processId to
        get instances of specific process type
      description:
        Optionally include a processId in the query params to filter by that
        process
      parameters:
        - $ref: '#/components/parameters/processIdQueryParam'
      responses:
        '200':
          description: An array of process instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessInstance'
              example:
                ProcessInstances:
                  type: array
                  example:
                    - id: 020229ae-9fd5-11ed-94af-0242ac150002
                      processRef: ReviewInvoice:1:bf20fe53-5548-11ed-9dd4-0242ac150002
                      initTime: 2023-01-31T08:45:11
                      lastChangeTime: 2023-05-23T02:34:00
                      state: running
                    - id: ff0f25e2-a792-11ed-b524-0242ac150002
                      processRef: invoice:1:bf2013f1-5548-11ed-9dd4-0242ac150002
                      initTime: 2023-11-08T17:23:00
                      lastChangeTime: 2023-11-08T17:23:00
                      state: suspended
        '404':
          description: Process instance not found
        '500':
          $ref: '#/components/responses/InternalServerError'
  /instances/{instanceId}:
    get:
      tags:
        - v1
        - developers
        - Runtime
      summary: return execution status details for a single process instance
      description:
        By passing in the process instance ID, get full details on its
        execution, including server logs emitted.
      parameters:
        - name: instanceId
          in: path
          description: Numeric ID of a process instance
          required: true
          style: simple
          explode: false
          example: 95aef406-3a7a-11e5-85b6-dafa20524153
          schema:
            type: integer
      responses:
        '200':
          description: A detailed process instance status object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessInstance'
        '404':
          description: Process instance not found
        '500':
          $ref: '#/components/responses/InternalServerError'
  /instances/{instanceId}/stop:
    post:
      tags:
        - v1
        - developers
        - Runtime
      summary: stops a process instance during execution
      operationId: stop
      description: Stops a process instance during execution
      parameters:
        - name: instanceId
          in: path
          description: Numeric ID of a process instance
          required: true
          style: simple
          explode: false
          example: 95aef406-3a7a-11e5-85b6-dafa20524153
          schema:
            type: integer
      responses:
        '201':
          description: Process instance stopped.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 95aef406-3a7a-11e5-85b6-dafa20524153
                    description: The unique process instance ID.
                  processRef:
                    type: string
                    example: invoice:1:15e97a1c-312d-11e5-aca3-a0e120524153
                    description: The process definition ID.
                  suspended:
                    type: boolean
                    example: false
                    description: States if process instance is suspended
                  ended:
                    type: boolean
                    example: true
                    description: States if process instance has ended
                  state:
                    type: string
                    example: stopped
                    description: Provides the execution state of the process instance
        '404':
          description: Process instance not found
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ProcessDefinition:
      type: object
      required:
        - name
        - type
        - version
      properties:
        name:
          type: string
          description: name of a process
        type:
          type: string
          enum:
            - None
            - Private
            - Public
        version:
          type: string
        isExecutable:
          type: boolean
          description: Specifies whether the Process is executable
        isClosed:
          type: boolean
          description:
            whether Messages and Events, not modeled in Process, can occur when
            the Process is executed or performed
        description:
          type: string
        processBody:
          $ref: '#/components/schemas/ListOfProperties'
      example:
        id: "invoice:1:bf2013f1-5548-11ed-9dd4-0242ac150002"
        key: "invoice"
        category: "http://www.omg.org/spec/BPMN/20100524/MODEL"
        version: 1
    Process:
      type: object
      properties:
        id:
          type: string
          description: generated by a system surrogate primary key
        processDefinition:
          $ref: '#/components/schemas/ProcessDefinition'
    ProcessInstancePayload:
      type: object
      required:
        - processStartedBy
      properties:
        processStartedBy:
          type: string
        InstanceValues:
          $ref: '#/components/schemas/ListOfProperties'
    ProcessInstance:
      type: object
      properties:
        id:
          type: integer
          description: generated by a system surrogate primary key
          example: 020229ae-9fd5-11ed-94af-0242ac150002
        processRef:
          type: string
          description: reference to the process definition
          example: ReviewInvoice:1:bf20fe53-5548-11ed-9dd4-0242ac150002
        initTime:
          type: string
          description: Initiation Timestamp
          example: 2023-11-08T17:23:00
        state:
          type: string
          description: see BPMN specification v.2.0 section 13.2.2
          example: running
        lastChangeTime:
          type: string
          description: last change Timestamp
          example: 2023-11-08T17:23:00
    ListOfProperties:
      type: array
      items:
        type: object
        properties:
          code:
            type: string
          value:
            type: string
        example:
          - creditor: "Niall"
            amount: 100
            invoiceNumber: 123
  parameters:
    processIdQueryParam:
      in: query
      name: processId
      required: false
      schema:
        type: string
        example: bf20fe53-5548-11ed-9dd4-0242ac150002
      description: The id for a defined process in the workflow engine.
    processIdParam:
      in: path
      name: processId
      required: true
      schema:
        type: string
        example: bf20fe53-5548-11ed-9dd4-0242ac150002
      description: The id for a defined process in the workflow engine.
  responses:
    InternalServerError:
      description: Internal server error, please contact administrator
